#- name: Install Nginx
#  ansible.builtin.dnf:
#    name: nginx
#    state: installed
#
#- name: Include App Pre-clean tasks
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: app_content_cleanup
#
#- name: Download App Content
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: download_app_content
#
#- name: Copy Nginx Configuration
#  ansible.builtin.template:
#    src: roboshop.conf
#    dest: /etc/nginx/roboshop.conf 
#
#- name: Restart Nginx Service
#  ansible.builtin.systemd:
#    name: nginx
#    state: restarted
#    enabled: true

- name: Disable nginx default version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 1.24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed
    
- name: Include App Pre-clean tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app_content_cleanup
    
- name: Copy Nginx config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/roboshop.conf


- name: Include download Pre-clean tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: download_app_content

- name: service start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd