- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Include App Pre-clean tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app_content_cleanup

- name: Download App Content
  ansible.builtin.import_role:
    name: common
    tasks_from: download_app_content

- name: Copy Nginx Configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf 

- name: Restart Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true