- name: Disable old redis module
  ansible.builtin.shell: dnf module disable redis -y ; dnf module enable redis:7 -y
  
- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: installed
    
- name: Replace localhost with IP
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.0'
    replace: '0.0.0.0'
      
      
- name: Import systemd service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd