- name: Disable Nginx older version
  ansible.builtin.shell: dnf install nginx -y

- name: enable Nginx 1.24
  ansible.builtin.shell: dnf module enable nginx:1.24 -y
  
- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed
    
- name: Copy nginx conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    
- name: Remove Default Content of Nginx
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Remove Default Content of Nginx
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and Extrect app code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: true


- name: restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enable: true
      
