- name: Disable Nginx older version
  ansible.builtin.shell: dnf install nginx -y

- name: enable Nginx 1.24
  ansible.builtin.shell: dnf module enable nginx:1.24 -y
  
- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed
    
- name: Copy nginx conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    
- name: clean up app code
  ansible.builtin.import_role:
    name: common
    tasks_from: cleanup_up_content

- name: download app code
  ansible.builtin.import_role:
    name: common
    tasks_from: download_app
    

      
