- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Import App Prerequisites
  ansible.builtin.include_tasks:
    file: app-prereq.yml

- name: Install Maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ role_name }}-1.0.jar {{ role_name }}.jar
  args:
    chdir: /app

- name: SystemD Service Setup
  ansible.builtin.include_tasks:
    file: systemd.yml



