- name: Setup SystemD service file
  ansible.builtin.template:
    src: "{{ role_name }}.service"
    dest: /etc/systemd/system/{{role_name}}.service

- name: Start Application
  ansible.builtin.systemd_service:
    name: "{{role_name}}"
    state: restarted
    enabled: true
    daemon_reload: true







